# Generated by Django 5.1.2 on 2024-10-22 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='smoking_and_beverages_usage',
            field=models.BooleanField(default=False),
        ),
    ]
