# Generated by Django 5.1.2 on 2024-11-02 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_hostel_smoking_and_beverages_usage'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='gender',
            field=models.IntegerField(choices=[(0, 'Female'), (1, 'Male'), (2, 'Both')], default=False),
            preserve_default=False,
        ),
    ]
