# Generated by Django 5.1.2 on 2024-11-05 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_hostel_latitude_hostel_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.FloatField(default=0.0),
        ),
    ]
