# Generated by Django 5.1.2 on 2025-01-05 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_hostel_four_seater_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='rating',
            field=models.FloatField(default=0),
        ),
    ]
