# Generated by Django 5.1.5 on 2025-01-19 03:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_blog_author_blog_date_blog_hook_blog_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='api.customusers'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('renter', 'Renter'), ('normal', 'Normal User')], default='normal', max_length=10),
        ),
    ]
