# Generated by Django 5.1.5 on 2025-01-19 03:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_hostel_user_alter_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hostels', to='api.customusers'),
        ),
    ]
