# Generated by Django 5.1.5 on 2025-01-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_hostel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='api.customusers'),
        ),
        migrations.AlterField(
            model_name='customusers',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('renter', 'Renter'), ('user', 'Normal User')], default='normal', max_length=10),
        ),
    ]
