# Generated by Django 5.1.5 on 2025-01-19 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_blog_author_alter_customusers_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='author',
            field=models.CharField(default='Anonymous', max_length=255),
        ),
    ]
