# Generated by Django 5.1.5 on 2025-01-19 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_alter_blog_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
