# Generated by Django 5.1.5 on 2025-01-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='blog_cover_images/'),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_cover_images/'),
        ),
        migrations.AlterField(
            model_name='hostelimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='hostel_additinal_images/'),
        ),
    ]
