# Generated by Django 5.1.5 on 2025-02-04 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_blog_image_alter_hostel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='first_aid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='hostel',
            name='sanitary_pad',
            field=models.BooleanField(default=False),
        ),
    ]
